# Generated by Django 4.0.2 on 2022-08-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_word_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=10),
            preserve_default=False,
        ),
    ]
